<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View</name>
   <tag></tag>
   <elementGuidId>3b31a334-d21c-4c99-bd7b-8fc9e6938851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.mr-1.btn-success.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b496771-a5fe-4eb4-a4a7-c9e646595183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>458f94f5-f0e3-4302-899e-28199e67eb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-1 btn-success btn-sm</value>
      <webElementGuid>db6e17bb-b4ef-474e-b792-b53ceefe8227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>b4633c2a-b0be-460a-a9f9-e19e0deeb26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsetContainer&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row mx-0&quot;]/div[@class=&quot;card card-style w-100 p-0 m-1&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;vertical-center col-2&quot;]/button[@class=&quot;btn mr-1 btn-success btn-sm&quot;]</value>
      <webElementGuid>62b13ae2-c240-4a34-8a6e-d45177c5f8ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>36ba9e9a-3871-4494-a50d-535f8a8410aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultsetContainer']/div/div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>0640036c-66ab-4311-b95c-ad108972d0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/preceding::button[1]</value>
      <webElementGuid>2c909d13-d7b2-4417-a251-ff28c2cadf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::button[1]</value>
      <webElementGuid>8c1cfc2c-c108-4787-8b55-f58c6d107c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>76f2715f-3d26-4044-b7d1-579c9d1ba1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>6438d632-a15a-4959-922d-b66bd1e26700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>e6faeebc-8d2a-4091-afa3-7d3b28c00d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
