<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Email</name>
   <tag></tag>
   <elementGuidId>3e01fc5c-5949-4e30-a2ee-a592239340cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.mb-1.btn-primary.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0517d2be-95b2-440b-b027-81b181dc5421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55578a83-4466-4327-b2d4-556107f76d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mb-1 btn-primary btn-sm</value>
      <webElementGuid>286ff849-5556-45f0-ac13-ed5d57f8fc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Email </value>
      <webElementGuid>955fdfdf-6d32-47b1-9e3c-02682cf597f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subsHeaderContainer&quot;)/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;card shadow-sm&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;m-0 p-0 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-0 pt-2 m-0 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;text-right col&quot;]/button[@class=&quot;btn mb-1 btn-primary btn-sm&quot;]</value>
      <webElementGuid>b98b610e-ff1f-4cbe-9172-8a8bb8950dc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>d2ff46c8-98bd-4c7a-99af-7dbdea9aa27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsHeaderContainer']/div[2]/div[2]/div/div/div/div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>bd40657f-0092-4886-9b81-877629b04375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address To*'])[1]/following::button[1]</value>
      <webElementGuid>bbe32219-81b6-4622-ace7-4747988cbc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Attachments Per Email*'])[1]/following::button[1]</value>
      <webElementGuid>b2ef82e4-abaf-4939-bb97-31627965ce87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Email Address'])[1]/preceding::button[1]</value>
      <webElementGuid>9a8b77ef-eb1c-43a6-9408-5d1c312e7f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>558b53da-1a4f-4b16-b8e2-f893e127c9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Email']/parent::*</value>
      <webElementGuid>3c641155-177f-41ba-85ed-b1cf4e347ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c33f2582-26a7-48d4-b830-e7ebeba3802f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Add Email ' or . = ' Add Email ')]</value>
      <webElementGuid>87cfe353-4825-4603-b26e-a0f8fec21b0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
