<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose applicable options_option1</name>
   <tag></tag>
   <elementGuidId>70c18aa9-657e-4b21-8b6d-735f3720661f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='moption']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c9f77b0-b366-42f1-921f-baa65f6d5a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b075491-e828-41c7-93af-c3305e6a1436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moption</value>
      <webElementGuid>01205358-342a-4941-b242-8ee116645de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option1</value>
      <webElementGuid>19f5faed-41d9-4106-9d82-21e35bf0c303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Option 1</value>
      <webElementGuid>b555fb5c-1543-465e-a487-c82f67132f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;row&quot;]/div[@class=&quot;main&quot;]/form[1]/fieldset[1]/input[@id=&quot;moption&quot;]</value>
      <webElementGuid>277e79df-0534-4d2b-9a1f-1744a868a9a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='moption']</value>
      <webElementGuid>9bdbb16a-cf6f-4398-9937-28f1e95c2832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>5831794d-78b3-445a-91e0-0c99167e9e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'moption' and @name = 'option1']</value>
      <webElementGuid>9a83aec8-b6cb-4858-bf62-bf875d0e04b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
