<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_lname</name>
   <tag></tag>
   <elementGuidId>6cc7c51c-4351-4fcc-a0cc-33178177c315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb3288d6-785b-4b1c-8a7f-e672282485f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>024e2b68-18c7-4842-9bab-88adcedfbeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>8513fbde-7601-4f1d-a65c-4e6f5d4d9e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>c92550ca-1e3e-4dce-8e3b-378a09b19268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>2847e676-22af-45f1-960b-37ea9653ade3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lname&quot;)</value>
      <webElementGuid>c32cabcf-307c-48b3-b94b-aa1455bcc24b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lname']</value>
      <webElementGuid>3483e353-0c53-4aaf-a48e-442e0b7b4d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input[2]</value>
      <webElementGuid>6c3f6739-d510-4c67-a0f2-cafbfa897595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lname' and @placeholder = 'Text' and @name = 'lname']</value>
      <webElementGuid>ff821f20-88d9-4f83-96e0-3587d9a6e272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
