<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a Transaction TypeFinancial D_fcbdd8</name>
   <tag></tag>
   <elementGuidId>558a3c0a-5bcc-47d5-bbf0-68070bbc482d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='__BVID__85']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__85</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__BVID__85' and (text() = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)' or . = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>431f000a-340e-4707-b248-b93e5e6d882a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>00b39362-549b-42e4-96a3-57144aa4aa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__85</value>
      <webElementGuid>93b494dd-fe45-422f-b7cb-725e64f9d79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)</value>
      <webElementGuid>02db4023-a96f-43cc-823a-84d4f3486d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__85&quot;)</value>
      <webElementGuid>608934af-2716-4c4f-aa13-fb5e9086ef1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__85']</value>
      <webElementGuid>23c37ba8-bf59-42b0-a9d2-b371dcb43503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsHeaderContainer']/div/div/div/div/select</value>
      <webElementGuid>01e22a51-187d-488b-bed2-0669d5fb0490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Subscription'])[1]/following::select[1]</value>
      <webElementGuid>5cad7750-3c7d-4eb6-a5cf-8da81f7312c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPAS-0.0.0'])[1]/following::select[1]</value>
      <webElementGuid>d3703f83-ffc3-4345-abaf-6a6e4cf86359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::select[1]</value>
      <webElementGuid>26f0bd5d-356f-4920-9bdb-3a7bf50a985e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::select[1]</value>
      <webElementGuid>71748673-7efc-450c-80a9-4bd0307b7541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>32059437-c827-4c44-8390-0e948d3087e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__85' and (text() = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)' or . = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)')]</value>
      <webElementGuid>1b7b751c-b7e1-4ffa-8de0-179ec4a0f846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
