<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add New Trading Partner</name>
   <tag></tag>
   <elementGuidId>dc0b78f8-66a8-4f0c-8a67-dc63bed00e78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/partner/00000000-0000-0000-0000-000000000000' and (text() = ' Add New Trading Partner ' or . = ' Add New Trading Partner ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e20a1d99-7be6-4a64-88f5-5895daf4ab96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/partner/00000000-0000-0000-0000-000000000000</value>
      <webElementGuid>c33eaffe-11a8-46f8-bda9-6b0fb4ac596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>5e4e72ef-6872-459c-ba76-bf0a20f5f36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>53ce07b4-b00b-44ad-b400-7f9e177ed2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add New Trading Partner </value>
      <webElementGuid>97a47829-6107-4346-a28e-d981b3cb8083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentsContainer&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;mw-100 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>052e77e0-b9e2-4cbc-856e-5f121842b5a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentsContainer']/div/div[3]/div/div/a</value>
      <webElementGuid>afe2b4ed-8821-4265-a61a-bdddf27ed1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add New Trading Partner')]</value>
      <webElementGuid>21044df6-2735-4b36-a5ef-530607cc46d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPS-0.0.0'])[1]/following::a[1]</value>
      <webElementGuid>1539141d-048d-4adb-9d74-8439f27fe796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trading Partners'])[2]/following::a[1]</value>
      <webElementGuid>cdda7a30-2df1-43b5-baa1-8806a8f349a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Filter'])[1]/preceding::a[1]</value>
      <webElementGuid>8b9dce74-6b70-4a2d-ac50-7e20d53bde2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPS-AS-0.0.0'])[1]/preceding::a[1]</value>
      <webElementGuid>808204f4-dcb4-4bbf-b915-b76610dd785e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New Trading Partner']/parent::*</value>
      <webElementGuid>06fdba7a-c196-4c27-82ae-bf6f2a072fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/partner/00000000-0000-0000-0000-000000000000')]</value>
      <webElementGuid>1b624e51-840f-4ade-9ffb-625763782f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>531921fd-2d50-4daf-a7b1-bed7fdacce5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/partner/00000000-0000-0000-0000-000000000000' and (text() = ' Add New Trading Partner ' or . = ' Add New Trading Partner ')]</value>
      <webElementGuid>be7d3dfb-ad7e-477d-aed4-09a585263d97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
