<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View (18)</name>
   <tag></tag>
   <elementGuidId>359e20d5-1585-4cb8-83d2-df327e18b2b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.mr-1.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa3eba79-e16f-46c3-ae79-e4604df3a0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77ce3fc3-3698-4031-9b9b-51b6b29a0b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-1 btn-success</value>
      <webElementGuid>9d38bd16-f540-4d55-ad91-b9f79dad1c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>64e26585-ee89-4b02-aace-e4abd9c6f4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transmissionContainer&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;p-0 m-0 col&quot;]/div[@class=&quot;card p-0 m-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row mx-0&quot;]/div[@class=&quot;card card-style w-100 p-0 m-1&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;vertical-center col-2&quot;]/button[@class=&quot;btn mr-1 btn-success&quot;]</value>
      <webElementGuid>9d80167d-35a9-41c0-a6d0-8bbc0f2c2ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>cc30fe98-7198-4917-bc05-e98d667be9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transmissionContainer']/div/div/div/div/div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>2ef92763-988f-45d9-bf27-41f5b9f41d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Format:'])[1]/following::button[1]</value>
      <webElementGuid>93228e37-ed14-491f-a301-5ed3c8bf14f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description:'])[1]/following::button[1]</value>
      <webElementGuid>48caa30e-5735-4e55-a544-95f2f74cccd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/preceding::button[1]</value>
      <webElementGuid>3cf96149-8b40-4dac-847a-525350e158c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[3]/preceding::button[1]</value>
      <webElementGuid>1f708397-b2c5-4404-a698-81a6c295eb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>4eec26e0-7752-4255-964e-959be53b734b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>f94de0a2-99a9-4944-b761-f60a0daea2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>9ef078de-f04b-4368-8241-533e862e6912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
