<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Email</name>
   <tag></tag>
   <elementGuidId>b81ec9af-237a-4908-a004-ddb914ead6d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.mb-1.btn-primary.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fa78f76-309b-42ee-b91f-57a93f990e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c0eb75d-aaa0-4784-9f7f-fb2d17ca0438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mb-1 btn-primary btn-sm</value>
      <webElementGuid>dd2b6217-a77d-42cb-b704-79baa3e9ec69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Email </value>
      <webElementGuid>bfd52b7d-6652-42be-ab60-ff7e3eb753e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subsHeaderContainer&quot;)/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;card shadow-sm&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;m-0 p-0 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-0 pt-2 m-0 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;text-right col&quot;]/button[@class=&quot;btn mb-1 btn-primary btn-sm&quot;]</value>
      <webElementGuid>a744cc8a-f0f3-45f5-83e9-5af1d7912eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>b9c68738-5a48-4c30-a301-4c4cca3930a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsHeaderContainer']/div[2]/div[2]/div/div/div/div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>301f305b-5b6c-4e19-aa30-b3df29c610ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address To*'])[1]/following::button[1]</value>
      <webElementGuid>f004ff58-d39c-4585-a869-a94116c0032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Attachments Per Email*'])[1]/following::button[1]</value>
      <webElementGuid>d2d64983-f182-4a8d-bc56-bc253239156e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='des@thekag.com'])[1]/preceding::button[1]</value>
      <webElementGuid>a2b4f7ce-93f3-43ac-80fb-db9b871918c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[1]</value>
      <webElementGuid>df32a525-4ca2-4e0e-90d9-a4cd0420d2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Email']/parent::*</value>
      <webElementGuid>37ef26a4-00bf-4b23-b15b-54e6c5fea117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>0e2730cc-7330-40b2-be07-5633d33872d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Add Email ' or . = ' Add Email ')]</value>
      <webElementGuid>baaf1464-b0ef-4f90-a6e2-f14c11627329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
