<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Transmission</name>
   <tag></tag>
   <elementGuidId>e8859884-518f-44a7-b254-20557fd6aef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.float-right.mt-n5.v2.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Add Transmission' or . = 'Add Transmission')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a47b65e-c03b-40b3-82e7-2096a78c9552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56a2a744-8eb8-4512-8781-3c44f37ab677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn float-right mt-n5 v2 btn-primary</value>
      <webElementGuid>b55d4948-8843-4013-80f3-0eb838b61ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Transmission</value>
      <webElementGuid>bc8fb75d-67ef-4899-a1fa-6b9048845cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transmissionContainer&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;p-0 m-0 col&quot;]/div[@class=&quot;card p-0 m-0&quot;]/div[@class=&quot;card-body&quot;]/button[@class=&quot;btn float-right mt-n5 v2 btn-primary&quot;]</value>
      <webElementGuid>ef01bfc5-85b0-45db-b2f3-7892d100f1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>e591adb4-76fd-4b0b-bac6-c95fd2c6e2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transmissionContainer']/div/div/div/div/button</value>
      <webElementGuid>762a8b9e-410d-4bca-b934-5546fd208e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transmission(s)'])[1]/following::button[1]</value>
      <webElementGuid>d500626b-7903-4568-a143-afeef051dfea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Bill Tos'])[1]/following::button[1]</value>
      <webElementGuid>5854cddf-0dba-4107-a742-e503e4434505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='per Page'])[2]/preceding::button[1]</value>
      <webElementGuid>6365841a-da51-48fa-bdef-d5beb9e3a1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[2]/preceding::button[1]</value>
      <webElementGuid>73c67bbc-1d4f-4235-967f-e0daee69a067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Transmission']/parent::*</value>
      <webElementGuid>0d3c4650-8bf1-4167-b0b2-77076993e451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/button</value>
      <webElementGuid>902b58b6-4827-457b-a863-674f701bcfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add Transmission' or . = 'Add Transmission')]</value>
      <webElementGuid>8df8a640-8942-408a-8214-fbc52988c92e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
