<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SourceBill To(s)Add Bill To51025per Pag_ac1b68</name>
   <tag></tag>
   <elementGuidId>0453174b-40f8-4653-9098-ab8b770a6993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sourceContainer']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sourceContainer > div.row > div.p-0.m-0.col > div.card.p-0.m-0 > div.card-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e490c568-4780-4ba7-b49b-787e149c4018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
      <webElementGuid>7b7b66ed-5265-4d44-b30b-459724a5bf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SourceBill To(s)Add Bill To51025per PageCodeNameDivisionAction«‹1›»Total: 0No Bill Tos</value>
      <webElementGuid>9ce2b500-c381-48f6-8b88-383c9d6917a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sourceContainer&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;p-0 m-0 col&quot;]/div[@class=&quot;card p-0 m-0&quot;]/div[@class=&quot;card-body&quot;]</value>
      <webElementGuid>60580b3f-0755-4504-a61d-74199d4c7279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sourceContainer']/div/div/div/div</value>
      <webElementGuid>964d7851-a344-472d-ab1d-897512a015ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::div[9]</value>
      <webElementGuid>699832f2-e280-4e9a-8803-477f31cfc8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery*'])[1]/following::div[10]</value>
      <webElementGuid>10a7ff13-8d36-4785-9dbf-d72667d40fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>1d6d8839-c513-43ff-a34f-8dbe3a57dc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SourceBill To(s)Add Bill To51025per PageCodeNameDivisionAction«‹1›»Total: 0No Bill Tos' or . = 'SourceBill To(s)Add Bill To51025per PageCodeNameDivisionAction«‹1›»Total: 0No Bill Tos')]</value>
      <webElementGuid>a0907b6f-2058-46af-946e-1c92e0b5ca45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
