<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frequency_time</name>
   <tag></tag>
   <elementGuidId>a921208f-14c5-4985-a30f-0e5dd020cf3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePicker2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePicker2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b53b006c-9469-4a49-af11-950f9ecbeb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b231a8ea-3b56-4597-98ca-773b053583e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e8b3a9bf-016e-47b5-bdb1-f94b047049a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prepend</name>
      <type>Main</type>
      <value>clock</value>
      <webElementGuid>6e14d7a7-cf1d-4450-a888-f3d8fb799f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePicker2</value>
      <webElementGuid>9ce7593a-f459-4b8f-8eb3-1a46ba5ab095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>df5f630d-8332-4673-b312-59bf10196ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Time</value>
      <webElementGuid>9bca0a67-fa58-45cc-af56-7875304ec463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePicker2&quot;)</value>
      <webElementGuid>3a489c84-a17b-44ed-858e-9501e8ddee8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePicker2']</value>
      <webElementGuid>0929e551-cafa-4e84-965e-c4cd026d24c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StartTimeValue']/div/input</value>
      <webElementGuid>43d06303-6867-45b8-9540-e8190caa1d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>83d0add6-efbe-44f5-9f48-3e6530c2f3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePicker2' and @name = 'time' and @placeholder = 'Select Time']</value>
      <webElementGuid>298c0282-3014-4397-b579-9625595d1b8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
