<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frequency_time_1</name>
   <tag></tag>
   <elementGuidId>8dfc4629-24b9-48e9-a951-5d49be894824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePicker3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePicker3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7537096-ae33-424b-9347-d92e0f69f831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d00712f4-fa22-4fa9-a0bc-3b497c3e36d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7ead5c64-3fd4-4a45-bffd-e4c0a2530e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prepend</name>
      <type>Main</type>
      <value>clock</value>
      <webElementGuid>4ed06eca-f1b7-4213-be0e-f206bfbd01e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePicker3</value>
      <webElementGuid>403b7542-355e-4150-bf56-8d8715f8fe79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>c02f6f6d-4083-4fca-9fdb-18dceeab0158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Time</value>
      <webElementGuid>ef656567-2860-44d3-a71a-4242c167390f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePicker3&quot;)</value>
      <webElementGuid>4d29e63a-b62e-48d3-9873-36150f485378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePicker3']</value>
      <webElementGuid>049885cc-da9a-4203-b67e-c03d2c665f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EndTimeValue']/div/input</value>
      <webElementGuid>20c55f9e-d4be-4ac6-8351-ad49d61f4cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>1db4635c-4c8b-44b8-b232-600aa96dfb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePicker3' and @name = 'time' and @placeholder = 'Select Time']</value>
      <webElementGuid>a3009b3a-283e-4bd7-963a-9d86d6f10bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
