<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frequency_date</name>
   <tag></tag>
   <elementGuidId>a01980e9-df77-439b-8c5c-7c66c6cc5f6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acfe7366-8fb2-4512-be47-c0efd8c84b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd4b0e67-5db8-4559-829f-17273ca026b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c2887dd7-a2c0-4162-9f71-ff9c7e47ecab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prepend</name>
      <type>Main</type>
      <value>clock</value>
      <webElementGuid>6706c223-fd46-410e-9514-0b4f13d42edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePicker</value>
      <webElementGuid>34a95f73-58eb-481a-ab16-12c05ac094ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>957abac6-6deb-4b32-9ddf-246dd0832f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Date</value>
      <webElementGuid>f903d7c0-92f9-4f82-8ac0-6908688bf5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePicker&quot;)</value>
      <webElementGuid>fb2d6222-b0ef-4d2b-b35a-349e16714cb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePicker']</value>
      <webElementGuid>835cddb1-abd6-4035-b7b3-28f7e6657f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StartDateValue']/div/input</value>
      <webElementGuid>31b10052-fbf2-485b-9a50-cb1c30dcec6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c1391405-b46a-4689-a044-11a6d8d2c35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePicker' and @name = 'date' and @placeholder = 'Select Date']</value>
      <webElementGuid>47e85eda-9ee1-41db-88a6-851feefe1325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
