<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frequency_date</name>
   <tag></tag>
   <elementGuidId>a01980e9-df77-439b-8c5c-7c66c6cc5f6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>189e90e8-4d18-4a7d-990b-34681eda138e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cf6f022-242d-402f-adef-b28a9a38d5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>07ca7dc6-cc70-4460-a07f-9e68d4ebe5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prepend</name>
      <type>Main</type>
      <value>clock</value>
      <webElementGuid>3e530749-301f-4f5a-b61c-bf367f830fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePicker</value>
      <webElementGuid>921892a5-b716-43bd-b362-7cdb03a38d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d01c613e-f121-42ef-a84d-a56377fb7ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Date</value>
      <webElementGuid>b9dc691c-08d3-4f7f-b1a2-f0ba545a8723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePicker&quot;)</value>
      <webElementGuid>5b90250c-5d6f-4381-b84c-6018932d89ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePicker']</value>
      <webElementGuid>40b2144b-e09b-4468-a4ed-da4455ab904f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StartDateValue']/div/input</value>
      <webElementGuid>8440d475-de09-4c66-87e1-0abc7f7c6467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3f2ee7df-f8c4-4e1f-b300-ec450e04b10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePicker' and @name = 'date' and @placeholder = 'Select Date']</value>
      <webElementGuid>fe9df51f-f071-48e9-aa82-d2485eadf961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
