<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description___BVID__91 (2)</name>
   <tag></tag>
   <elementGuidId>276d0b01-7d7e-4a2e-9024-6d56ef0580b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__91</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='descriptionControl']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14415bc8-1f0d-4b30-9bb4-c5c85dd5c199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>986d367e-16cf-456c-a83e-963128494e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pr-0 form-control</value>
      <webElementGuid>8f4fe3df-3167-442c-8ce7-b60e2b7b5269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__91</value>
      <webElementGuid>b8a7afb6-4034-4d36-a1a7-c931469760bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__91&quot;)</value>
      <webElementGuid>70c9b44c-2134-46cb-be4c-8a8358131a39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__91']</value>
      <webElementGuid>d6a880cc-d6f3-413b-95cd-7779e36d51f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='descriptionControl']/input</value>
      <webElementGuid>d9e7589f-f310-437a-9ab0-f2e092404bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>592d6053-bb90-4664-b7ba-43b66a43c89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '__BVID__91']</value>
      <webElementGuid>9c7dbc6e-854f-4e5b-9bdb-20621ba7aef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
