<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please correct the following error(s)_933826</name>
   <tag></tag>
   <elementGuidId>cc37b2e0-6b57-45c6-babb-72b797cd9bea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a445972-da57-499c-8829-f7efb3ecd0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-large</value>
      <webElementGuid>a98650e8-8b3b-4952-8892-ebcf8a910d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>baf6f145-85d6-4152-8b54-9fec90031a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Trading Partner Name</value>
      <webElementGuid>ff97de77-e672-4704-a690-05a2b96ff7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>c621db99-99bc-4ecf-ab6c-a1331d06b67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-large&quot;)</value>
      <webElementGuid>f1e7b8af-b0be-4d5f-938e-5c7ab125f9ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-large']</value>
      <webElementGuid>711e9162-bc8d-453b-8253-2a8d202a89c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentsContainer']/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>a282eb13-c94a-4d17-8919-b56a7c158b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>50e301b2-f9f1-4696-b344-eab563ca2533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-large' and @type = 'text' and @placeholder = 'Trading Partner Name']</value>
      <webElementGuid>cf76daef-484f-40e5-b475-df81e126ec02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
