<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select.Real TimeScheduled (5)</name>
   <tag></tag>
   <elementGuidId>dc9f4f32-5fab-4a10-b5c3-044d0523bf0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__90</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='deliveryControl']/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3141cdb7-b293-478c-88fc-249c10dee13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>788c7eeb-94ce-4c8a-8dba-ef353066e1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__90</value>
      <webElementGuid>c4e06736-0ff4-41ec-8030-7880adc83e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...Real TimeScheduled</value>
      <webElementGuid>1470058e-80db-44b2-adac-8c311f117c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__90&quot;)</value>
      <webElementGuid>657e7c9b-ddb8-4282-9a15-372577032b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__90']</value>
      <webElementGuid>3fdfbf0d-1546-43bb-acd3-ef56f553505d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deliveryControl']/select</value>
      <webElementGuid>eeb42a14-cd75-4fac-b616-620b7a8a93ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[2]</value>
      <webElementGuid>2fc999cb-234f-4a75-8e8c-0a5ed39cb410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery*'])[1]/following::select[2]</value>
      <webElementGuid>a7d3be6e-68f2-4fb8-8edc-bb67c2b52566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/preceding::select[1]</value>
      <webElementGuid>2025bdff-126e-40d6-b0ae-9f6818bcc8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill To(s)'])[1]/preceding::select[1]</value>
      <webElementGuid>80e2d35d-3a84-40d2-9cba-1181ecb47b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>2e9d4829-2499-4be7-838a-77704074f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__90' and (text() = 'Select...Real TimeScheduled' or . = 'Select...Real TimeScheduled')]</value>
      <webElementGuid>e8d2cb89-7594-42e7-8d91-4160fe71f948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
