<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select.EmailFile Transfer ProtocolNe_92efe9</name>
   <tag></tag>
   <elementGuidId>ead29d88-afd2-46e4-85c8-934118c98b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__BVID__133' and (text() = 'Select...EmailFile Transfer ProtocolNetwork Share' or . = 'Select...EmailFile Transfer ProtocolNetwork Share')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__133</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0789899d-4046-466c-9aa3-4249ef924dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>8f5fce37-146a-4025-8bc6-fc37d187b9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__133</value>
      <webElementGuid>4fbbca9f-3cf2-4b0b-bade-6db7f91e7c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...EmailFile Transfer ProtocolNetwork Share</value>
      <webElementGuid>8b9d7e06-7a47-4594-abf2-17e25b67ad31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__133&quot;)</value>
      <webElementGuid>7c3d707e-d137-4d83-b62a-4356cc193c45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__133']</value>
      <webElementGuid>e1b18b55-dbda-4b88-9a4c-92f3ef7d2053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TransmissionItems']/div/span/select</value>
      <webElementGuid>514a6e46-01fa-4d2e-a71d-2be73e196f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>2d8318a0-474b-413a-b1a1-83666a1c559c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[3]</value>
      <webElementGuid>c5c0c3b0-2a71-4280-8224-57d34eec6154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[3]</value>
      <webElementGuid>b5d5eac4-d696-4a87-8fdf-ad6d09e48a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dd5ca6e1-f61e-4c04-9476-e5f9e747f021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__133' and (text() = 'Select...EmailFile Transfer ProtocolNetwork Share' or . = 'Select...EmailFile Transfer ProtocolNetwork Share')]</value>
      <webElementGuid>d5b32f54-9e73-4671-93ca-04f3f19b1d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
