<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a Transaction TypeFinancial D_642f55 (3)</name>
   <tag></tag>
   <elementGuidId>df4efdbf-6996-4f96-ad20-dd8e02e92505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__85</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subsHeaderContainer']/div/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9293cf8-829f-473d-b308-53f61855f1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>3feea261-fb69-4e31-9402-43dad951b0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__85</value>
      <webElementGuid>541e4867-37fb-4700-a8d5-c61535455450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)</value>
      <webElementGuid>62c0baca-bc3b-43f0-a06c-480dfe12fbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__85&quot;)</value>
      <webElementGuid>4c1bfc02-7be5-4ba7-a6d5-2f73bbff2b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__85']</value>
      <webElementGuid>45142cab-92d2-4dbc-81f5-4290233a546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsHeaderContainer']/div/div/div/div/select</value>
      <webElementGuid>3ffc544e-76f2-4591-9cef-aadfa3ebf1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Subscription'])[1]/following::select[1]</value>
      <webElementGuid>cab8c8bc-486d-47e9-86a2-2dfcece9cccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPAS-0.0.0'])[1]/following::select[1]</value>
      <webElementGuid>1478fb9f-d8f0-4755-ad8a-6319d5767184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::select[1]</value>
      <webElementGuid>1741e7a5-c4e2-40ab-b718-202b9aab03b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::select[1]</value>
      <webElementGuid>143ab39a-62eb-45b9-b3ec-bc109e20b02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>df1e0de9-ec60-4898-ac26-c7017c38ecb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__85' and (text() = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)' or . = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)')]</value>
      <webElementGuid>3be3afc8-1c3d-465b-85e9-fd8846dfa2d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
