<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select.Real TimeScheduled (2)</name>
   <tag></tag>
   <elementGuidId>260c959c-2508-4da7-b3df-684ff79a6674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__90</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='deliveryControl']/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b39608c4-60ff-4a4e-b6de-849173bbd043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>1e31bab7-44c6-42fa-afd3-cd120f59c98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__90</value>
      <webElementGuid>db73aee0-ae2c-4a60-9866-018d944b83b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...Real TimeScheduled</value>
      <webElementGuid>2ec2221a-5e48-4fe5-b674-e6ef24a7ad14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__90&quot;)</value>
      <webElementGuid>751eff33-f5d2-4c2b-8ce7-d38d666f98a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__90']</value>
      <webElementGuid>b8649e16-0743-419f-bb57-8982ad3e3dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deliveryControl']/select</value>
      <webElementGuid>f462e3a7-d100-4adf-b39b-3eea0fbf0b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[2]</value>
      <webElementGuid>7d6f63e0-f87b-412b-b60b-a7054b09a66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery*'])[1]/following::select[2]</value>
      <webElementGuid>6ededf55-0fb9-41f5-b3e3-471ad8a5a2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/preceding::select[1]</value>
      <webElementGuid>c50aa1fa-7df0-4497-8620-a7c40add253f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill To(s)'])[1]/preceding::select[1]</value>
      <webElementGuid>eaae9ed3-9bbb-4fa2-8383-aa0be08e2fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>2b75a620-ff03-4bca-8086-0f48a3d24365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__90' and (text() = 'Select...Real TimeScheduled' or . = 'Select...Real TimeScheduled')]</value>
      <webElementGuid>0e45275e-348d-4f7f-857c-a81ae10f6f6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
