<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a Transaction TypeFinancial D_642f55</name>
   <tag></tag>
   <elementGuidId>39f18190-51e0-46f5-93b5-9b2841675b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__85</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subsHeaderContainer']/div/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>29369b3e-6f94-4828-9aae-1906d1db6271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>0530d074-4910-495d-987a-c62da907d26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__85</value>
      <webElementGuid>424f6e13-d92e-4a05-b811-c4db252106c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)</value>
      <webElementGuid>9ec71740-664f-4685-9c1c-959845f78071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__85&quot;)</value>
      <webElementGuid>ef5e1474-711e-41e9-b17a-7743c2a559a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__85']</value>
      <webElementGuid>cd4824d4-f251-4ac9-b63b-fca1496687ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsHeaderContainer']/div/div/div/div/select</value>
      <webElementGuid>af4a8a3c-2044-4aff-9ef6-597e6d899895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Subscription'])[1]/following::select[1]</value>
      <webElementGuid>7e24b1c3-1732-4f97-88f2-01a540336124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPAS-0.0.0'])[1]/following::select[1]</value>
      <webElementGuid>e7485919-57fe-483c-ba92-e839ca78449b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::select[1]</value>
      <webElementGuid>05eced19-285f-4b6f-866a-30ddc3896c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::select[1]</value>
      <webElementGuid>55d739a2-a20b-4023-a7be-41d012fb4f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1ff0de1b-5725-4e75-b5c2-4bc13e12b2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__85' and (text() = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)' or . = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)')]</value>
      <webElementGuid>e5ff58c7-fdc1-48ff-93be-41e2a2be0012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
