<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a Transaction TypeFinancial D_642f55 (1)</name>
   <tag></tag>
   <elementGuidId>cfb64fd9-7428-4c05-9711-d55dd28df9c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='__BVID__85']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__85</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>438cd235-5e3d-458d-a6df-ed2c49e4583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>81137341-15d7-463a-8ce4-48be1c71cf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__85</value>
      <webElementGuid>a4b5e412-8808-43ae-a312-87c2731a8964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)</value>
      <webElementGuid>586ceef3-7849-4d1e-bf62-1c9457150188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__85&quot;)</value>
      <webElementGuid>d23276bb-393b-49d5-a62e-3a8dfb063b43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__85']</value>
      <webElementGuid>e741d7be-4492-4650-8910-b0e65755a508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsHeaderContainer']/div/div/div/div/select</value>
      <webElementGuid>91e2d391-e101-4101-8aac-b8848824cee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Subscription'])[1]/following::select[1]</value>
      <webElementGuid>a352a346-e1fa-45c0-a127-02228bcd734b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPAS-0.0.0'])[1]/following::select[1]</value>
      <webElementGuid>ab2e9332-6f8a-4fd3-9988-8e60dbbac7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::select[1]</value>
      <webElementGuid>7466b7bd-f8da-4fe6-a514-1f267772be4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::select[1]</value>
      <webElementGuid>dbd8156b-a110-4a49-9c12-542abf4b2021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>612ebf54-f607-49e5-b71d-2731f6175147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__85' and (text() = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)' or . = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Inventory Management (Inventory)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)')]</value>
      <webElementGuid>96869219-4c72-47da-85c5-6456c3af9c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
