<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a Transaction TypeFinancial D_fcbdd8 (1)</name>
   <tag></tag>
   <elementGuidId>e29ab90f-4fa7-408b-bc69-6214f57f99f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__BVID__87' and (text() = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)' or . = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__87</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='__BVID__87']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__87</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__87&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__87']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsHeaderContainer']/div/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Subscription'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPAS-0.0.0'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__87' and (text() = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)' or . = 'Select a Transaction Type*Financial Data - Accruals (FIN-ACC)Financial Data - Invoice (FIN-INV)Functional Acknowledgement (FA)Invoice (INV)Load Tender (LT)Load Tender Response (LTR)')]</value>
   </webElementXpaths>
</WebElementEntity>
