<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_21STCENT (7)</name>
   <tag></tag>
   <elementGuidId>a8d5e5f7-fd7a-46a3-be2f-6f389a605832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='FDG'])[2]/following::td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c15582c2-3904-4a48-a2a4-7cf8e9238e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a7b6a67c-8eb3-4bf9-8ce3-776427570623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>7fd417fc-dac1-40ba-bf94-bbe528aa4498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21STCENT</value>
      <webElementGuid>aeff4d59-d4be-4886-b46e-87e01f9e843b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__113&quot;)/tbody[1]/tr[3]/td[1]</value>
      <webElementGuid>04d27be6-cb76-42db-828a-dcf57f87382f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__113']/tbody/tr[3]/td</value>
      <webElementGuid>4416a7a9-741c-4221-a701-c7cd7a7d94e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FDG'])[2]/following::td[2]</value>
      <webElementGuid>37e8051d-fc5c-4284-86d3-daa904528bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FDG'])[1]/following::td[6]</value>
      <webElementGuid>d020bfc4-1af3-407c-bf29-640e3f165c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FDG'])[3]/preceding::td[2]</value>
      <webElementGuid>c80c8aaa-3673-4d25-b032-8c1fa9855553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[2]/preceding::td[4]</value>
      <webElementGuid>542d7dff-2352-4409-bdf4-b0d6764500d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21STCENT']/parent::*</value>
      <webElementGuid>e6761656-c366-40b1-aaba-4f77cbc7a7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>774f68be-dab0-441c-92df-6f1887c03856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '21STCENT' or . = '21STCENT')]</value>
      <webElementGuid>b5249046-c00c-493d-a84c-9184cf1f8fa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
