<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>2b28d92b-b9e8-41af-a66e-274bf0b95990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_ds-QYo6_ApuTwbkPrZu6-AY9']/g-menu/g-menu-item/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/search?q=Automation&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwiO0uuM4v_3AhWbSTABHa2NDm8Q_AUoAHoECAMQCQ' and (text() = 'Видеа' or . = 'Видеа')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a_Videos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05645151-510e-44b9-ba40-adcc9bed524a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=Automation&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwiO0uuM4v_3AhWbSTABHa2NDm8Q_AUoAHoECAMQCQ</value>
      <webElementGuid>73553df9-7496-4d9c-9d75-b5dfc67581ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>dfe26d57-80e0-4af9-a54c-bcda6943d748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d120a5a0-75f9-4c0c-bc7f-6adb911e87e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Видеа</value>
      <webElementGuid>876303cb-a91f-4f49-8818-2f67b481018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_ds-QYo6_ApuTwbkPrZu6-AY9&quot;)/g-menu[@class=&quot;cF4V5c zriOQb UU8UAb gLSAk rShyOb&quot;]/g-menu-item[@class=&quot;ErsxPb gvybPb&quot;]/div[@class=&quot;znKVS OSrXXb tnhqA&quot;]/a[1]</value>
      <webElementGuid>ccee359e-6656-4c63-8c5e-57da14dbe54c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_ds-QYo6_ApuTwbkPrZu6-AY9']/g-menu/g-menu-item/div/a</value>
      <webElementGuid>a614ee57-9e96-43db-a201-00f95cc3d067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Видеа')]</value>
      <webElementGuid>17072bb9-44c5-46a2-854a-76ee1e26adc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Дословно'])[1]/following::a[1]</value>
      <webElementGuid>c532b33f-feaf-4451-8acb-961b339a0922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сите резултати'])[2]/following::a[2]</value>
      <webElementGuid>706297e4-d90e-4372-a3a2-f1a5fa3fc0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Летови'])[1]/preceding::a[1]</value>
      <webElementGuid>88be6c0f-ef97-4d91-a1ad-632b7ffc788a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Финансии'])[1]/preceding::a[2]</value>
      <webElementGuid>970519e1-7d91-4868-90a4-640b7d04dd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Видеа']/parent::*</value>
      <webElementGuid>d8232556-30e4-4f73-ba60-e9cc24bbe7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=Automation&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwiO0uuM4v_3AhWbSTABHa2NDm8Q_AUoAHoECAMQCQ')]</value>
      <webElementGuid>7e50ad3e-bf48-4423-a3b4-da44af13bedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/g-menu/g-menu-item/div/a</value>
      <webElementGuid>c59be0ae-427f-423a-817f-e84b17e7150d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=Automation&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwiO0uuM4v_3AhWbSTABHa2NDm8Q_AUoAHoECAMQCQ' and (text() = 'Видеа' or . = 'Видеа')]</value>
      <webElementGuid>004a3881-b40e-4eee-a021-5c2bb62e2b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
