<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>69a4a23c-5660-48a3-9717-ed94edd45920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/span/g-popup/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.GOE98c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e5b2753-7917-417e-a556-ad9dc2e1e021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>LgbsSe</value>
      <webElementGuid>9606b6d5-4c27-4b14-913c-451499353148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GOE98c</value>
      <webElementGuid>87d06e50-6eea-4530-9d02-6c2d14dd75b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Повеќе</value>
      <webElementGuid>1f5e2ade-4c90-4e87-9597-c3a19ea18da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/span[@class=&quot;hdtb-mitem&quot;]/g-popup[1]/div[@class=&quot;rIbAWc&quot;]/div[@class=&quot;GOE98c&quot;]</value>
      <webElementGuid>f2352824-8fae-4d8f-b62f-bd85bbfd272c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/span/g-popup/div/div</value>
      <webElementGuid>f0a8d6af-2915-4f24-a414-ae076edd3c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Книги'])[1]/following::div[2]</value>
      <webElementGuid>43821f26-381a-4e61-b6a3-75f16c92ed89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Карти'])[1]/following::div[3]</value>
      <webElementGuid>2bda6c96-73eb-40f9-9198-1df4054bcd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Видеа'])[1]/preceding::div[1]</value>
      <webElementGuid>c3e9d3a5-d6fa-4d9f-af9e-282bc05a27d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Летови'])[1]/preceding::div[2]</value>
      <webElementGuid>655af020-5dbc-42d2-90f6-56a7d0d939fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Повеќе']/parent::*</value>
      <webElementGuid>7733af73-0495-43ba-adbe-7e6c14555310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//g-popup/div/div</value>
      <webElementGuid>593e08c9-84de-4894-84db-3a3d6f9ba986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Повеќе' or . = 'Повеќе')]</value>
      <webElementGuid>8d4be81f-78f5-4668-a9ff-95c9786d1757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
